networks:
    ioquake3:
        external: false

services:
    ioquake3:
        container_name: ioquake3
        build:
            context: .
        restart: always
        env_file:
            - .env
        environment:
            - MOTD
            - RCON_PASS
            - EXTRA_ARGS
        networks:
            - ioquake3
        volumes:
            - ${BASEQ3_DIR}:/quake/baseq3
            - ${CONFIG_DIR}:/config
        ports:
            - ${QUAKE_PORT}:27960/udp
